[package]
name = "kairos-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version="0.30.0", features = ["native-tls"] }
futures-util = "0.3.34"

sea-orm = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Solana
solana-sdk = { version = "4.1.0", features = ["full"] }
solana-client = "4.3.0"
solana-commitment-config = "3.1.1"
anchor-client = "1.1.2"
anchor-lang = "1.1.2"

borsh = { version = "1", features = ["derive"] }
base64 = "0.22"
chrono = "0.4"

# Internal
kairos-db = { path = "../kairos-db" }
migration = { path = "../kairos-db/migration" }
perp = { path = "../programs/perp/programs/perp", features = ["no-entrypoint"] }
liquidity-pool = { path = "../programs/liquidity-pool/programs/liquidity-pool", features = ["no-entrypoint"] }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
serde_json = "1"
