//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "positions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub position_pubkey: String,
    #[sea_orm(column_type = "Text")]
    pub owner: String,
    #[sea_orm(column_type = "Text")]
    pub market: String,
    #[sea_orm(column_type = "Text")]
    pub side: String,
    pub collateral: i64,
    pub notional: i64,
    pub entry_price: i64,
    pub entry_funding_index: i64,
    pub opened_at: DateTimeWithTimeZone,
    pub closed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
