skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
perp = "26rUyPQbEjw26Bt6jBiM5RwzUbRbXE9qBXnnwrGxAEFo"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
