skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
liquidity_pool = "86Pd3Qq2TTuakU85RH6knQC1tBU2NiZDhHLuKjq55Hdi"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
