skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
liquidity_pool = "6yxEJYRsMSc1FuzLoWDWpfrDWPvmGH34kFD9qPFiPTHy"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
