skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
liquidity_pool = "EvfapscrVw8DTdMWKk6udmgbb5esZz7fF83ZPiHdYWKn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
