use borsh::BorshDeserialize;
use rpc::AnchorAccount;
use solana_sdk::pubkey::Pubkey;

// Structs, enums and discriminators below this point are generated by build.rs from the perp
// program's Anchor IDL — do not hand-edit them here.
include!(concat!(env!("OUT_DIR"), "/perp_accounts.rs"));

impl PositionType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Long => "long",
            Self::Short => "short",
        }
    }
}
