use borsh::BorshDeserialize;
use solana_sdk::pubkey::Pubkey;

/// Marks a type as an Anchor `#[event]` struct, tagging it with the 8-byte
/// discriminator anchor prefixes onto every `Program data:` log for it.
pub trait AnchorEvent: BorshDeserialize {
    const DISCRIMINATOR: [u8; 8];
}

// Structs, discriminators and the `PerpEvent` enum below this point are generated by
// build.rs from the perp program's Anchor IDL — do not hand-edit them here. Add a new
// event and it shows up on the next `cargo build` once the IDL has it.
include!(concat!(env!("OUT_DIR"), "/perp_events.rs"));

impl MarketInitialized {
    /// `symbol` is a fixed 16-byte, nul-padded ASCII field on-chain.
    pub fn symbol_str(&self) -> String {
        String::from_utf8_lossy(&self.symbol)
            .trim_end_matches('\0')
            .to_string()
    }
}
