[package]
name = "kairos-ingestor"
version = "0.1.0"
edition = "2024"


[dependencies]
dotenv = "0.15.0"
# async
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version="0.30.0", features = ["native-tls"] }
futures-util = "0.3.34"
reqwest = { version = "0.12", features = ["json"] }

# Solana
solana-sdk = { version = "4.1.0", features = ["full"] }
solana-client = "4.3.0"
anchor-client = "1.1.2"

# serialization
borsh = { version = "1", features = ["derive"] }
base64 = "0.22"
bincode = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# internal
kairos-db = { path = "../kairos-db" }
kairos-config = { path = "../kairos-config" }
migration = { path = "../kairos-db/migration", optional = true }
perp = { path = "../programs/perp/programs/perp", features = ["no-entrypoint"] }
liquidity-pool = { path = "../programs/liquidity-pool/programs/liquidity-pool", features = ["no-entrypoint"] }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
derive_more = {version = "2.1.1", features = ["from", "display"]}

sea-orm = { version = "1.1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"], optional = true }

