use borsh::BorshDeserialize;
use solana_sdk::pubkey::Pubkey;

use crate::parser::accounts::AnchorAccount;

// Generated by build.rs from the liquidity-pool program's Anchor IDL — do not hand-edit.
include!(concat!(env!("OUT_DIR"), "/lp_accounts.rs"));
