use borsh::BorshDeserialize;
use solana_sdk::pubkey::Pubkey;

use crate::parser::events::AnchorEvent;

// Generated by build.rs from the liquidity-pool program's Anchor IDL — do not hand-edit.
include!(concat!(env!("OUT_DIR"), "/lp_events.rs"));
